package com.dawidrichert.database.repositories;

import com.dawidrichert.database.models.User;
import com.dawidrichert.unitofwork.UnitOfWork;

import javax.sql.DataSource;
import java.sql.*;

public class UserRepository extends BaseRepository<User> {

    private static final String tableName = "Users";
    private static final String col_Id = "Id";
    private static final String col_PersonId = "PersonId";
    private static final String col_Login = "Login";
    private static final String col_Password = "Password";

    public UserRepository(DataSource dataSource, UnitOfWork unitOfWork) {
        super(dataSource, unitOfWork, tableName, col_Id);
    }

    @Override
    public long persistAdd(User user) {
        try(Connection connection = dataSource.getConnection()) {
            String sql;
            sql  = String.format("INSERT INTO %s (", tableName);
            sql += String.format("%s, ", col_PersonId);
            sql += String.format("%s, ", col_Login);
            sql += String.format("%s) VALUES (?, ?, ?)", col_Password);

            try(PreparedStatement preparedStatement = connection.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS)) {
                preparedStatement.setLong(1, user.getPersonId());
                preparedStatement.setString(2, user.getLogin());
                preparedStatement.setString(3, user.getPassword());
                preparedStatement.executeUpdate();
                return getLastInsertedId(preparedStatement);
            }
        } catch(Exception e) {
            e.printStackTrace();
        }
        return -1;
    }

    @Override
    public void persistUpdate(User user) {
        try(Connection connection = dataSource.getConnection()) {
            String sql;
            sql  = String.format ("UPDATE %s SET ", tableName);
            sql += String.format ("%s=?, ", col_PersonId);
            sql += String.format ("%s=?, ", col_Login);
            sql += String.format ("%s=? ", col_Password);
            sql += String.format ("WHERE %s=?", col_Id);

            try(PreparedStatement preparedStatement = connection.prepareStatement(sql)) {
                preparedStatement.setLong(1, user.getPersonId());
                preparedStatement.setString(2, user.getLogin());
                preparedStatement.setString(3, user.getPassword());
                preparedStatement.setLong(4, user.getId());
                preparedStatement.executeUpdate();
            }
        } catch(Exception e) {
            e.printStackTrace();
        }
    }

    @Override
    protected void createTableIfNotExists() {
        try(Connection connection = dataSource.getConnection()) {
            String sql;
            sql = String.format("CREATE TABLE IF NOT EXISTS %s (", tableName);
            sql += String.format("%s BIGINT GENERATED BY DEFAULT AS IDENTITY, ", col_Id);
            sql += String.format("%s BIGINT NOT NULL, ", col_PersonId);
            sql += String.format("%s VARCHAR(256) NOT NULL, ", col_Login);
            sql += String.format("%s VARCHAR(256) NOT NULL)", col_Password);

            try(PreparedStatement preparedStatement = connection.prepareStatement(sql)) {
                preparedStatement.executeUpdate();
            }
        } catch(Exception e) {
            e.printStackTrace();
        }
    }

    @Override
    protected User mapResultSetToModel(ResultSet resultSet) throws SQLException {
        return new User(
                resultSet.getLong(col_Id),
                resultSet.getLong(col_PersonId),
                resultSet.getString(col_Login),
                resultSet.getString(col_Password));
    }
}
